export const chalkboard = {
  id: "chalkboard",
  defaultPalette: "craie",
  name: "Tableau Noir",
  defaultPalette: "forest",
  description: "Ardoise, craie, poussiere, ecole",
  preview: "linear-gradient(135deg, #1a2a1a 0%, #1e3320 50%, #152515 100%)",

  css: {
    "--th-surface": "rgba(255,255,255,0.05)",
    "--th-surface-hover": "rgba(255,255,255,0.08)",
    "--th-surface-dim": "rgba(255,255,255,0.02)",
    "--th-surface-subtle": "rgba(255,255,255,0.03)",
    "--th-surface-faint": "rgba(255,255,255,0.012)",
    "--th-border": "rgba(255,255,255,0.1)",
    "--th-border-dim": "rgba(255,255,255,0.04)",
    "--th-border-subtle": "rgba(255,255,255,0.06)",
    "--th-border-strong": "rgba(255,255,255,0.15)",
    "--th-text": "#e8e8d8",
    "--th-text-secondary": "rgba(232,232,216,0.6)",
    "--th-text-tertiary": "rgba(232,232,216,0.45)",
    "--th-text-muted": "rgba(232,232,216,0.3)",
    "--th-text-dim": "rgba(232,232,216,0.2)",
    "--th-text-faint": "rgba(232,232,216,0.12)",
    "--th-blur": "0px",
    "--th-radius": "2px",
    "--th-radius-sm": "2px",
    "--th-radius-xs": "1px",
    "--th-radius-pill": "2px",
    "--th-bar-bg": "rgba(255,255,255,0.04)",
    "--th-bar-prev": "rgba(255,255,200,0.08)",
    "--th-font-body": "'Caveat',cursive",
    "--th-font-mono": "'Caveat',cursive",
    "--th-glass-bg": "rgba(25,40,25,0.92)",
    "--th-glass-blur": "blur(8px)",
    "--th-glass-border": "rgba(255,255,255,0.08)",
    "--th-tooltip-bg": "#1a2a1a",
    "--th-tooltip-border": "rgba(255,255,255,0.08)",
  },

  effects: {
    stars: false, orbs: false, grain: false, spotlights: false,
    confetti: false, fireworks: false, scanlines: false, grid: false,
    vhs: false, filmGrain: false,
    chalkDust: true, chalkTexture: true, chalkboardBg: true,
  },

  cssExtra: `
@import url('https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap');
.th-chalk-texture{position:fixed;inset:0;pointer-events:none;z-index:0;background:repeating-conic-gradient(rgba(255,255,255,0.008) 0% 25%,transparent 0% 50%) 0 0/3px 3px}
.glass{border:1px dashed rgba(255,255,255,0.12)!important;background:rgba(25,40,25,0.9)!important;backdrop-filter:blur(8px)!important;-webkit-backdrop-filter:blur(8px)!important;box-shadow:inset 0 0 30px rgba(0,0,0,0.2)!important}
.recap-root [style*="border-radius"]{backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important}
.recap-root [style*="borderRadius"]{backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important}
.recap-root h1,.recap-root h2,.recap-root h3{font-style:italic!important;text-shadow:1px 1px 0 rgba(255,255,255,0.05)!important;filter:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='c'%3E%3CfeTurbulence baseFrequency='0.04' numOctaves='4' type='fractalNoise'/%3E%3CfeDisplacementMap in='SourceGraphic' scale='2'/%3E%3C/filter%3E%3C/svg%3E#c")!important}
.recap-root::before{content:'';position:fixed;top:6px;left:6px;right:6px;bottom:6px;border:3px solid rgba(180,150,100,0.12);border-radius:2px;pointer-events:none;z-index:200;box-shadow:inset 0 0 20px rgba(0,0,0,0.15)}
`,

  labels: {
    brand: "WRAPPARR",
    viewed: "notes",
    episodes: "chap.",
    hours: "d'etude",
    monthlyActivity: "Bulletin mensuel",
    favoriteDay: "Jour de cours",
    consumptionTime: "Heure de revision",
    goldenMonth: "Mois d'examen",
    recordDay: "Devoir parfait",
    whenYouConsume: "Quand tu",
    consume: "revises",
    budgetTitle: "Le budget de",
    yourFilms: "tes lecons",
    ratingsTitle: "Tes notes de",
    worldTitle: "a travers",
    theWorld: "le programme",
    countriesRepresented: "matieres etudiees",
    bestNote: "20/20",
    worstNote: "A revoir",
    mostExpensive: "Cours particuliers",
    leastExpensive: "Exercices maison",
    bestROI: "Meilleur ratio effort/resultat",
    avgBudget: "Cout moyen par matiere",
    totalCumulated: "cout total",
    distributionTitle: "Repartition des matieres",
    budgetPerFilm: "Cout par matiere",
    on: "sur",
    films: "lecons",
    rated: "notees",
    average: "moyenne generale",
    viewsUnit: "seances",
    hoursUnit: "h",
    ofTotal: "du programme",
    viewing: "de revision",
  },
}
