export const cinemaClassic = {
  id: "cinema-classic",
  defaultPalette: "pellicule",
  name: "Cinéma Classic",
  description: "Pellicule, grain, ambiance salle obscure",
  preview: "linear-gradient(135deg, #1a0f05, #2a1a0a)",

  css: {
    "--th-surface": "rgba(255,220,160,0.06)",
    "--th-surface-hover": "rgba(255,220,160,0.1)",
    "--th-surface-dim": "rgba(255,220,160,0.02)",
    "--th-surface-subtle": "rgba(255,220,160,0.03)",
    "--th-surface-faint": "rgba(255,220,160,0.01)",
    "--th-border": "rgba(255,220,160,0.15)",
    "--th-border-dim": "rgba(255,220,160,0.06)",
    "--th-border-subtle": "rgba(255,220,160,0.08)",
    "--th-border-strong": "rgba(255,220,160,0.22)",
    "--th-text": "#ffeedd",
    "--th-text-secondary": "rgba(255,238,221,0.6)",
    "--th-text-tertiary": "rgba(255,238,221,0.45)",
    "--th-text-muted": "rgba(255,238,221,0.3)",
    "--th-text-dim": "rgba(255,238,221,0.22)",
    "--th-text-faint": "rgba(255,238,221,0.15)",
    "--th-blur": "8px",
    "--th-radius": "8px",
    "--th-radius-sm": "6px",
    "--th-radius-xs": "4px",
    "--th-radius-pill": "16px",
    "--th-bar-bg": "rgba(255,220,160,0.04)",
    "--th-bar-prev": "rgba(255,220,160,0.12)",
    "--th-font-body": "'Playfair Display',Georgia,serif",
    "--th-font-mono": "'Courier Prime',Courier,monospace",
    "--th-glass-bg": "rgba(30,20,10,0.75)",
    "--th-glass-border": "rgba(255,220,160,0.15)",
    "--th-glass-blur": "blur(8px)",
    "--th-tooltip-bg": "#1a0f05",
    "--th-tooltip-border": "rgba(255,220,160,0.15)",
  },

  effects: {
    stars: false,
    orbs: true,
    grain: true,
    spotlights: true,
    confetti: true,
    fireworks: false,
    scanlines: false,
    grid: false,
    vhs: false,
    filmGrain: true,
  },

  cssExtra: `
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700;800&family=Courier+Prime:wght@400;700&display=swap');
.th-film-grain{position:fixed;inset:0;pointer-events:none;z-index:44;opacity:0.08;mix-blend-mode:overlay;animation:th-film-flicker 0.15s infinite}
@keyframes th-film-flicker{0%{opacity:0.06}50%{opacity:0.1}100%{opacity:0.07}}
.th-vignette{position:fixed;inset:0;pointer-events:none;z-index:43;background:radial-gradient(ellipse at center,transparent 50%,rgba(0,0,0,0.5) 100%)}
`,

  labels: {
    brand: "WRAPPARR",
    viewed: "projetes",
    episodes: "ep.",
    hours: "en salle",
    monthlyActivity: "Programmation mensuelle",
    favoriteDay: "Jour de seance",
    consumptionTime: "Horaire de projection",
    goldenMonth: "Mois d'or",
    recordDay: "Seance marathon",
    whenYouConsume: "Quand tu",
    consume: "regardes",
    budgetTitle: "Le budget de",
    yourFilms: "tes bobines",
    ratingsTitle: "Tes critiques",
    worldTitle: "à travers",
    theWorld: "le monde",
    countriesRepresented: "pays à l'affiche",
    bestNote: "Palme d'or",
    worstNote: "Navet de l'année",
    mostExpensive: "Grosses productions",
    leastExpensive: "Films indépendants",
    bestROI: "Meilleur succès au box-office",
    avgBudget: "Budget moyen des films projetés",
    totalCumulated: "budget total",
    distributionTitle: "Répartition des productions",
    budgetPerFilm: "Budget par bobine",
    on: "sur",
    films: "films",
    rated: "critiques",
    average: "note moyenne",
    viewsUnit: "séances",
    hoursUnit: "h",
    ofTotal: "de la saison",
    viewing: "de projection",
  },
}
