export const comic = {
  id: "comic",
  defaultPalette: "pop-art",
  name: "Comic Book",
  description: "Halftone, cases, onomatopees, BD pop",
  preview: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",

  css: {
    "--th-surface": "rgba(255,255,255,0.07)",
    "--th-surface-hover": "rgba(255,255,255,0.12)",
    "--th-surface-dim": "rgba(255,255,255,0.03)",
    "--th-surface-subtle": "rgba(255,255,255,0.04)",
    "--th-surface-faint": "rgba(255,255,255,0.02)",
    "--th-border": "rgba(255,255,255,0.2)",
    "--th-border-dim": "rgba(255,255,255,0.08)",
    "--th-border-subtle": "rgba(255,255,255,0.12)",
    "--th-border-strong": "rgba(255,255,255,0.3)",
    "--th-text": "#ffffff",
    "--th-text-secondary": "rgba(255,255,255,0.65)",
    "--th-text-tertiary": "rgba(255,255,255,0.5)",
    "--th-text-muted": "rgba(255,255,255,0.35)",
    "--th-text-dim": "rgba(255,255,255,0.22)",
    "--th-text-faint": "rgba(255,255,255,0.14)",
    "--th-blur": "0px",
    "--th-radius": "0px",
    "--th-radius-sm": "0px",
    "--th-radius-xs": "0px",
    "--th-radius-pill": "4px",
    "--th-bar-bg": "rgba(255,255,255,0.05)",
    "--th-bar-prev": "rgba(255,255,0,0.12)",
    "--th-font-body": "'Bangers',cursive",
    "--th-font-mono": "'Share Tech Mono',monospace",
    "--th-glass-bg": "rgba(10,10,30,0.92)",
    "--th-glass-border": "rgba(255,255,255,0.25)",
    "--th-glass-blur": "blur(0px)",
    "--th-tooltip-bg": "#0a0a1e",
    "--th-tooltip-border": "rgba(255,255,255,0.2)",
  },

  effects: {
    stars: false, orbs: false, grain: false, spotlights: true,
    confetti: true, fireworks: false, scanlines: false, grid: false,
    vhs: false, filmGrain: false,
    halftone: true, comicBorders: true,
  },

  cssExtra: `
@import url('https://fonts.googleapis.com/css2?family=Bangers&family=Share+Tech+Mono&display=swap');
.th-halftone{position:fixed;inset:0;pointer-events:none;z-index:44;opacity:0.06;mix-blend-mode:multiply;background-image:radial-gradient(circle,rgba(255,255,255,0.8) 1px,transparent 1px);background-size:4px 4px}
.glass{border:3px solid rgba(255,255,255,0.25)!important;box-shadow:5px 5px 0 rgba(0,0,0,0.6)!important;border-radius:0!important}
.recap-root h1,.recap-root h2,.recap-root h3{text-transform:uppercase!important;letter-spacing:0.04em!important;-webkit-text-stroke:1px rgba(0,0,0,0.5)!important;text-shadow:3px 3px 0 rgba(0,0,0,0.7),-1px -1px 0 rgba(0,0,0,0.3)!important}
.recap-root h1 span,.recap-root h2 span{-webkit-text-stroke:inherit!important}
`,

  labels: {
    brand: "WRAPPARR",
    viewed: "lus",
    episodes: "ep.",
    hours: "d'aventure",
    monthlyActivity: "Planche mensuelle",
    favoriteDay: "Jour de parution",
    consumptionTime: "Heure de lecture",
    goldenMonth: "Arc narratif majeur",
    recordDay: "Double page legendaire",
    whenYouConsume: "Quand tu",
    consume: "devores",
    budgetTitle: "Le cout de",
    yourFilms: "tes planches",
    ratingsTitle: "Tes critiques",
    worldTitle: "a travers",
    theWorld: "le multivers",
    countriesRepresented: "univers explores",
    bestNote: "Collector",
    worstNote: "Flop editorial",
    mostExpensive: "Editions limitees",
    leastExpensive: "Pocket",
    bestROI: "Meilleur ratio ventes/tirage",
    avgBudget: "Prix moyen par tome",
    totalCumulated: "budget total",
    distributionTitle: "Repartition des tomes",
    budgetPerFilm: "Prix par tome",
    on: "sur",
    films: "tomes",
    rated: "critiques",
    average: "note moyenne",
    viewsUnit: "lectures",
    hoursUnit: "h",
    ofTotal: "de la serie",
    viewing: "de lecture",
  },
}
