export const sinCity = {
  id: "sin-city",
  defaultPalette: "basin-city",
  name: "Sin City",
  description: "Noir total, contraste dur, touche de couleur",
  preview: "linear-gradient(135deg, #000000 0%, #1a1a1a 40%, #000000 100%)",

  css: {
    "--th-surface": "rgba(255,255,255,0.08)",
    "--th-surface-hover": "rgba(255,255,255,0.12)",
    "--th-surface-dim": "rgba(255,255,255,0.03)",
    "--th-surface-subtle": "rgba(255,255,255,0.04)",
    "--th-surface-faint": "rgba(255,255,255,0.02)",
    "--th-border": "rgba(255,255,255,0.14)",
    "--th-border-dim": "rgba(255,255,255,0.06)",
    "--th-border-subtle": "rgba(255,255,255,0.08)",
    "--th-border-strong": "rgba(255,255,255,0.2)",
    "--th-text": "#ffffff",
    "--th-text-secondary": "rgba(255,255,255,0.6)",
    "--th-text-tertiary": "rgba(255,255,255,0.45)",
    "--th-text-muted": "rgba(255,255,255,0.3)",
    "--th-text-dim": "rgba(255,255,255,0.2)",
    "--th-text-faint": "rgba(255,255,255,0.13)",
    "--th-blur": "0px",
    "--th-radius": "0px",
    "--th-radius-sm": "0px",
    "--th-radius-xs": "0px",
    "--th-radius-pill": "0px",
    "--th-bar-bg": "rgba(255,255,255,0.06)",
    "--th-bar-prev": "rgba(255,255,255,0.1)",
    "--th-font-body": "'Bebas Neue',Impact,sans-serif",
    "--th-font-mono": "'Share Tech Mono',monospace",
    "--th-glass-bg": "rgba(8,8,8,0.9)",
    "--th-glass-border": "rgba(255,255,255,0.1)",
    "--th-glass-blur": "blur(0px)",
    "--th-tooltip-bg": "#080808",
    "--th-tooltip-border": "rgba(255,255,255,0.1)",
  },

  effects: {
    stars: false,
    orbs: false,
    grain: false,
    spotlights: false,
    confetti: false,
    fireworks: false,
    scanlines: false,
    grid: false,
    vhs: false,
    filmGrain: true,
    noirRain: true,
    noirDesaturate: true,
    noirBlinds: true,
    bloodDrips: true,
  },

  cssExtra: `
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Share+Tech+Mono&display=swap');
.th-film-grain{position:fixed;inset:0;pointer-events:none;z-index:44;opacity:0.1;mix-blend-mode:overlay;animation:th-noir-grain 0.12s steps(1) infinite}
@keyframes th-noir-grain{0%{opacity:0.07}50%{opacity:0.12}100%{opacity:0.08}}
.th-vignette{position:fixed;inset:0;pointer-events:none;z-index:43;background:radial-gradient(ellipse at center,transparent 25%,rgba(0,0,0,0.7) 100%)}
.recap-root.th-noir-on{filter:contrast(1.3)!important}
.recap-root.th-noir-on img,.recap-root.th-noir-on svg:not([data-keep-color]),.recap-root.th-noir-on canvas{filter:saturate(0)!important}
.recap-root h2,.recap-root h1,.recap-root h3{text-transform:uppercase!important;letter-spacing:0.08em!important;text-shadow:2px 2px 0 rgba(0,0,0,0.9),4px 4px 0 rgba(0,0,0,0.4)!important}
.recap-root h2 span[style],.recap-root h1 span[style]{filter:saturate(3) brightness(1.3)!important}
.glass{border-left:3px solid rgba(255,255,255,0.15)!important;border-right:none!important;border-top:none!important;border-bottom:none!important;border-radius:0!important}
`,

  labels: {
    brand: "WRAPPARR",
    viewed: "traques",
    episodes: "ep.",
    hours: "dans la nuit",
    monthlyActivity: "Rapport mensuel",
    favoriteDay: "Nuit de garde",
    consumptionTime: "Heure du crime",
    goldenMonth: "Mois noir",
    recordDay: "Nuit blanche",
    whenYouConsume: "Quand tu",
    consume: "surveilles",
    budgetTitle: "Le prix du",
    yourFilms: "sang",
    ratingsTitle: "Le verdict",
    worldTitle: "a travers",
    theWorld: "Basin City",
    countriesRepresented: "quartiers infiltres",
    bestNote: "Justice rendue",
    worstNote: "Bavure",
    mostExpensive: "Gros calibres",
    leastExpensive: "Petites frappes",
    bestROI: "Meilleur retour de flamme",
    avgBudget: "Prix moyen de la traque",
    totalCumulated: "cout total",
    distributionTitle: "Repartition des affaires",
    budgetPerFilm: "Prix par affaire",
    on: "sur",
    films: "affaires",
    rated: "jugees",
    average: "note du jury",
    viewsUnit: "filatures",
    hoursUnit: "h",
    ofTotal: "du dossier",
    viewing: "de planque",
  },
}
